version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-jessie
    steps:
      - checkout
      - run:
          name: install
          command: yarn 
      - run:
          name: test
          command: yarn coverage
